language: python
cache: pip

python:
- '2.7'
- '3.5'
- '3.6'

install:
- pip install -r requirements.txt
- pip install coverage
- pip install codecov

script:
- python -m coverage run -a -m unittest discover tests
- python -m coverage report
- pip install cibuildwheel==0.10.1
- cibuildwheel --output-dir wheelhouse

after_success:
  - codecov

deploy:
  provider: pypi
  user: "SimLeek"
